# Generated by Django 5.0.6 on 2024-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate_registration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
