# Generated by Django 5.0.6 on 2024-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_advocate_registration_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipc_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('punishment', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
