# Generated by Django 5.0.6 on 2024-06-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_messages_delete_chat_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='advocate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.advocate_registration'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.user_registration'),
        ),
    ]
