# Generated by Django 5.0.6 on 2024-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0008_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='accepted',
            field=models.CharField(default='pending', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='posted_date',
            field=models.DateField(null=True),
        ),
    ]
