# Generated by Django 5.0.6 on 2024-06-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0010_rename_accepted_cases_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_work_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('accepted_date', models.DateField(null=True)),
                ('advocate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.advocate_registration')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.cases')),
            ],
        ),
    ]
