# Generated by Django 5.0.6 on 2024-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0011_request_work_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_work_admin',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
