# Generated by Django 5.0.6 on 2024-06-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0012_request_work_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_work_admin',
            name='accepted_date_user',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request_work_admin',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.user_registration'),
        ),
    ]
