# Generated by Django 5.0.6 on 2024-06-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0014_alter_request_work_admin_accepted_date_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_work_admin',
            name='user_id',
        ),
    ]
