# Generated by Django 5.0.6 on 2024-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0016_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
