# Generated by Django 5.0.6 on 2024-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0017_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_work_admin',
            name='accepted_date_user',
            field=models.DateField(null=True),
        ),
    ]
