# Generated by Django 5.0.6 on 2024-06-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0018_alter_request_work_admin_accepted_date_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='advocate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.advocate_registration'),
        ),
    ]
