# Generated by Django 5.0.6 on 2024-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0020_messages_status_alter_messages_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
    ]
