# Generated by Django 5.0.6 on 2024-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0022_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='accepted_date_user',
            field=models.DateField(null=True),
        ),
    ]
