# Generated by Django 5.0.6 on 2024-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0023_cases_accepted_date_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
