# Generated by Django 5.0.6 on 2024-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0024_feedbacks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate_registration',
            name='fees',
            field=models.IntegerField(null=True),
        ),
    ]
