# Generated by Django 5.0.6 on 2024-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0026_alter_advocate_registration_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate_registration',
            name='cases_won',
            field=models.IntegerField(default=0),
        ),
    ]
