
from django.contrib import admin
from django.urls import path
from legal import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index),
    path('login',views.login),
    path('registration_user',views.registration_user),
    path('registration_advocate',views.registration_advocate),
    path('admin_home',views.admin_home),
    path('advocate_home',views.advocate_home),
    path('user_home',views.user_home),
    path('advocate_requests',views.advocate_requests),
    path('advocate_approval',views.advocate_approval),
    path('advocate_reject',views.advocate_reject),
    path('view_advocates_admin',views.view_advocates_admin),
    path('view_users_admin',views.view_users_admin),
    path('remove_advocate',views.remove_advocate),
    path('remove_user',views.remove_user),
    path('add_ipc_section',views.add_ipc_section),
    path('update_ipc_section',views.update_ipc_section),
    path('view_ipc_section_admin',views.view_ipc_section_admin),
    path('remove_ipc_section',views.remove_ipc_section),
    path('view_advocates_user',views.view_advocates_user),
    path('message_advocate',views.message_advocate),
    path('view_ipc_sections_user',views.view_ipc_sections_user),
    path('post_case_user',views.post_case_user),
    path('view_post_cases_user',views.view_post_cases_user),
    path('delete_post_cases_user',views.delete_post_cases_user),
    path('view_cases_advocate',views.view_cases_advocate),
    path('request_work_advocate',views.request_work_advocate),
    path('view_request_from_advocate',views.view_request_from_advocate),
    path('accept_request_from_advocate',views.accept_request_from_advocate),
    path('reject_request_from_advocate',views.reject_request_from_advocate),
    path('view_request_from_user_advocate',views.view_request_from_user_advocate),
    path('accept_request_from_user_admin',views.accept_request_from_user_admin),
    path('reject_request_from_user_admin',views.reject_request_from_user_admin),
    path('view_replies_from_advocate',views.view_replies_from_advocate),
    path('delete_posted_case_user',views.delete_posted_case_user),
    path('feedbacks_user',views.feedbacks_user),
    path('view_feedbacks_user',views.view_feedbacks_user),
    path('view_feedbacks_advocate',views.view_feedbacks_advocate),
    path('view_feedbacks_admin',views.view_feedbacks_admin),
    path('view_work_confirmation_advocate',views.view_work_confirmation_advocate),
    path('edit_profile_advocates',views.edit_profile_advocates),
]
